# -*- coding: utf-8 -*-
"""Montecarlo simulation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ey4aUC50U7fXtYFymfkcnqJESmXwhSZG
"""

import numpy as np
import pandas as pd

#Parámetros

num_simulations = 100000
initial_investment_mean = 10000
initial_investment_std = 2000
annual_return_mean = 0.12
annual_return_std = 0.20
min_duration = 1
max_duration = 5

#Determinar las distribuciones de probabilidad de las variables independientes

initial_investment = np.random.normal(initial_investment_mean, initial_investment_std, num_simulations)
annual_return = np.random.normal(annual_return_mean, annual_return_std, num_simulations)
investment_duration = np.random.uniform(min_duration, max_duration, num_simulations)

#Relacionar las variables independientes a través de la ecuación de rendimiento

final_investment = initial_investment * (1 + annual_return) ** investment_duration

#DataFrame con los resultados de la simulación

Results_df = pd.DataFrame()

Results_df['Initial investment'] = initial_investment
Results_df['Annual return'] = annual_return
Results_df['Investment duration'] = investment_duration
Results_df['Final investment'] = final_investment

#Exportar resultados a excel

with pd.ExcelWriter('Prueba Simulación de Montecarlo.xlsx') as writer:
  Results_df.to_excel(writer,sheet_name= 'Montecarlo simulation',index=False)