# -*- coding: utf-8 -*-
"""PCA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qhrFkTcj2ToXunNjRv5bTqyuMACTJyk_
"""

import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from numpy.linalg import eig

Data=pd.read_excel('/content/Iris.xlsx')

X_cols=	['sepallength',	'sepalwidth',	'petallength', 'petalwidth']

ss=StandardScaler

#normalizamos los datos
Data[X_cols] = StandardScaler().fit_transform(Data[X_cols])

print(Data[X_cols].cov())

valores, vectores = eig(Data[X_cols].cov())

valores, vectores

proyectados = pd.DataFrame(Data[X_cols] @ vectores.T)

pca_iris = PCA(n_components=2)

principalComponents_iris = pca_iris.fit_transform(Data[X_cols])

principal_iris_Df = pd.DataFrame(data = principalComponents_iris
             , columns = ['principal component 1', 'principal component 2'])

print('Explained variation per principal component: {}'.format(pca_iris.explained_variance_ratio_))