# -*- coding: utf-8 -*-
"""Programming_visuals

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gK6rEGf8fW0XD36WvYJ5AGZqps7xi4Tt
"""

#Importar Librerias
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import pyplot
import seaborn as sns

#Leemos la data
Data=pd.read_excel("/content/Data cursos chía.xlsx")

#Gráfico con pyplot - matplotlib
X=['R', 'Python', 'Scala', 'SQL']
Y=[456, 899, 500, 345]
Colores=['#1D6D56', '#C61458', '#FF7121', '#6B007B']
plt.bar(X,Y, color=Colores)
plt.title("Usuarios de lenguajes de programación")
plt.xlabel("Lenguajes de programación")
plt.ylabel("Número de usuarios")

sns.barplot(x=X, y=Y)
plt.title("Usuarios de lenguajes de programación")
plt.xlabel("Lenguajes de programación")
plt.ylabel("Número de usuarios")

# Datos
grupos = ['G1', 'G2', 'G3', 'G4', 'G5']
valores1 = [12, 19, 14, 27, 16]
valores2 = [21, 30, 15, 17, 20]
values3 = [15, 23, 12, 11, 15]

fig, ax = plt.subplots()

# Gráfico de barras apiladas
ax.bar(grupos, valores1)
ax.bar(grupos, valores2, bottom = valores1)

Data_2=Data[['GENERO', 'Calificación']]

# Graficar datos apilados de modo que las columnas 'one' y 'two' estén apiladas
Data_2.plot(kind='bar',stacked=True,title="The title of my graph")



